"""
多向量混合搜索完整示例
这个示例其实是多种类型向量混合，使用bm25进行搜索，并没有使用Bm25+语义搜索的融合

"""

from pymilvus import (
    MilvusClient, DataType, Function, FunctionType, AnnSearchRequest
)
import random

# ==================== 1. 连接 Milvus 服务 ====================
client = MilvusClient(
    uri="http://localhost:19530",
    token="root:Milvus"  # 默认管理员账号密码
)

# ==================== 2. 创建 Schema ====================
# 初始化 schema，禁用自动 ID（手动提供主键）
schema = client.create_schema(auto_id=False)

# 添加字段到 schema
# 主键字段：存储产品 ID
schema.add_field(
    field_name="id",
    datatype=DataType.INT64,
    is_primary=True,
    description="product id"
)

# 文本字段：存储产品描述，启用分析器以支持全文搜索
schema.add_field(
    field_name="text",
    datatype=DataType.VARCHAR,
    max_length=1000,
    enable_analyzer=True,  # 启用分析器，为 BM25 做准备
    description="raw text of product description"
)

# 文本密集向量字段：用于语义搜索（768维）
schema.add_field(
    field_name="text_dense",
    datatype=DataType.FLOAT_VECTOR,
    dim=768,
    description="text dense embedding"
)

# 文本稀疏向量字段：存储 BM25 自动生成的稀疏向量
schema.add_field(
    field_name="text_sparse",
    datatype=DataType.SPARSE_FLOAT_VECTOR,
    description="text sparse embedding auto-generated by the built-in BM25 function"
)

# 图像密集向量字段：用于多模态图像搜索（512维）
schema.add_field(
    field_name="image_dense",
    datatype=DataType.FLOAT_VECTOR,
    dim=512,
    description="image dense embedding"
)

# ==================== 3. 添加 BM25 函数 ====================
# BM25 函数将 text 字段自动转换为稀疏向量，存储到 text_sparse 字段
bm25_function = Function(
    name="text_bm25_emb",
    input_field_names=["text"],      # 输入：原始文本字段
    output_field_names=["text_sparse"],  # 输出：稀疏向量字段
    function_type=FunctionType.BM25,     # 函数类型：BM25 全文搜索
)
schema.add_function(bm25_function)

# ==================== 4. 配置索引参数 ====================
index_params = client.prepare_index_params()

# 索引1：文本密集向量（语义搜索）
index_params.add_index(
    field_name="text_dense",
    index_name="text_dense_index",
    index_type="AUTOINDEX",   # 自动选择最优索引类型
    metric_type="IP"          # 内积相似度
)

# 索引2：文本稀疏向量（BM25 全文搜索）
index_params.add_index(
    field_name="text_sparse",
    index_name="text_sparse_index",
    index_type="SPARSE_INVERTED_INDEX",  # 稀疏向量专用倒排索引
    metric_type="BM25",                   # BM25 相关性评分
    params={"inverted_index_algo": "DAAT_MAXSCORE"}  # 查询算法：MaxScore
    # 可选算法: "DAAT_WAND" 或 "TAAT_NAIVE"
)

# 索引3：图像密集向量（多模态图像搜索）
index_params.add_index(
    field_name="image_dense",
    index_name="image_dense_index",
    index_type="AUTOINDEX",   # 自动选择最优索引类型
    metric_type="IP"          # 内积相似度
)

# ==================== 5. 创建集合 ====================
client.create_collection(
    collection_name="my_collection",
    schema=schema,
    index_params=index_params
)

print("✓ 集合创建成功")

# ==================== 6. 准备辅助函数 ====================
def generate_dense_vector(dim):
    """生成随机密集向量（实际应用中应使用真实 Embedding 模型）"""
    return [random.random() for _ in range(dim)]

# ==================== 7. 插入数据 ====================
# 准备示例数据
data = [
    {
        "id": 0,
        "text": "Red cotton t-shirt with round neck",
        "text_dense": generate_dense_vector(768),   # 文本语义向量
        "image_dense": generate_dense_vector(512)   # 图像特征向量
    },
    {
        "id": 1,
        "text": "Wireless noise-cancelling over-ear headphones",
        "text_dense": generate_dense_vector(768),
        "image_dense": generate_dense_vector(512)
    },
    {
        "id": 2,
        "text": "Stainless steel water bottle, 500ml",
        "text_dense": generate_dense_vector(768),
        "image_dense": generate_dense_vector(512)
    }
]

# 插入数据（BM25 函数会自动为 text_sparse 字段生成稀疏向量）
res = client.insert(
    collection_name="my_collection",
    data=data
)

print(f"✓ 数据插入成功，插入 {len(data)} 条记录")

# ==================== 8. 执行混合搜索 ====================
print("\n" + "="*50)
print("开始执行混合搜索")
print("="*50)

# 8.1 准备查询数据
query_text = "white headphones, quiet and comfortable"  # 查询文本
query_dense_vector = generate_dense_vector(768)        # 语义搜索查询向量
query_multimodal_vector = generate_dense_vector(512)   # 多模态搜索查询向量

# 8.2 创建多个搜索请求

# 请求1：文本语义搜索（密集向量）
search_param_1 = {
    "data": [query_dense_vector],           # 查询向量
    "anns_field": "text_dense",             # 在文本密集向量字段上搜索
    "param": {"nprobe": 10},                # 探测聚类数（精度/性能平衡）
    "limit": 2                              # 每个请求返回 2 条结果
}
request_1 = AnnSearchRequest(**search_param_1)

# 请求2：全文搜索（稀疏向量，BM25）
search_param_2 = {
    "data": [query_text],                   # 原始文本，自动转换为稀疏向量
    "anns_field": "text_sparse",            # 在 BM25 生成的稀疏向量上搜索
    "limit": 2                              # 返回 2 条结果
}
request_2 = AnnSearchRequest(**search_param_2)

# 请求3：文本到图像搜索（多模态）
search_param_3 = {
    "data": [query_multimodal_vector],      # 多模态查询向量
    "anns_field": "image_dense",            # 在图像密集向量字段上搜索
    "param": {"nprobe": 10},                # 探测聚类数
    "limit": 2                              # 返回 2 条结果
}
request_3 = AnnSearchRequest(**search_param_3)

# 组合所有搜索请求
reqs = [request_1, request_2, request_3]

# 8.3 配置重排序器（RRF - 倒数排名融合）
ranker = Function(
    name="rrf",
    input_field_names=[],      # 重排序函数必须为空列表
    function_type=FunctionType.RERANK,
    params={
        "reranker": "rrf",     # 使用 RRF 算法
        "k": 60               # 平滑参数（可选，默认 60）
    }
)
"""
也可以写成
reranker = RRFRanker(k=rrf_k)
"""


# 8.4 执行混合搜索
# 注意：3个搜索请求共返回 6 条结果（2×3），RRF 会融合并返回前 2 条
result = client.hybrid_search(
    collection_name="my_collection",
    reqs=reqs,
    ranker=ranker,
    limit=2,                   # 最终返回 2 条结果
    output_fields=["text"]     # 返回结果中包含 text 字段
)

# 最简单去重：按 ID 保留最高分
unique_results = {}
for hits in result:
    for hit in hits:
        hit_id = hit['id']
        # 如果 ID 不存在，或者当前分数更高，则保留
        if hit_id not in unique_results or hit['distance'] > unique_results[hit_id]['distance']:
            unique_results[hit_id] = hit


#接下来可以对RRF融合后的结果再进行rerank

# ==================== 9. 输出搜索结果 ====================
print("\n搜索结果：")
for idx, hits in enumerate(unique_results):
    print(f"\n查询 {idx + 1}: {query_text}")
    print(f"找到 {len(hits)} 条相关结果：")
    for hit in hits:
        print(f"  - ID: {hit['id']}, 距离分数: {hit['distance']:.4f}")
        if 'text' in hit:
            print(f"    文本: {hit['text']}")

# ==================== 10. 高级用法：时区设置 ====================
# 如果集合中有 TIMESTAMPTZ 字段，可以临时设置时区
# 示例代码（实际使用时需要先添加 TIMESTAMPTZ 字段）

"""
# 带时区的混合搜索示例
res_with_timezone = client.hybrid_search(
    collection_name="my_collection",
    reqs=reqs,
    ranker=ranker,
    limit=2,
    timezone="America/Havana"  # IANA 时区标识符
)
"""

print("\n✓ 混合搜索完成")

# ==================== 可选：清理资源 ====================
# 如需删除集合，取消注释以下代码
# client.drop_collection(collection_name="my_collection")
# print("集合已删除")


"""
多向量字段设计
text_dense：768维，用于语义理解
text_sparse：BM25 自动生成，用于关键词匹配
image_dense：512维，用于图像检索

三种搜索类型
搜索类型	向量字段	查询方式	适用场景
语义搜索	text_dense	密集向量	理解查询意图
全文搜索	text_sparse	原始文本	精确关键词匹配
多模态搜索	image_dense	密集向量	文本搜图像
"""